#!/bin/bash


#SBATCH --job-name=dvd-test      # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=1        # cpu-cores per task
#SBATCH --mem=4G                 # total memory per node
#SBATCH --gres=gpu:1             # number of gpus per node
#SBATCH --partition=gpu          # partition requested
#SBATCH --time=08:00:00          # total run time limit (HH:MM:SS)
#SBATCH --output=out.txt         # file for script's standard output
#SBATCH --mail-type=begin        # send mail when job begins
#SBATCH --mail-type=end          # send mail when job ends
#SBATCH --mail-type=fail         # send mail if job fails
#SBATCH --mail-user=david.alvarez.rosa@yandex.com


source .venv/bin/activate
python train.py --dataset refcoco \
       --model_id model \
       --image_root /scratch/gobi1/datasets/MSCOCO/images/train2014/ \
       --pretrained \
       --workers 4 \
       --batch_size 16
