#!/bin/bash

# Sync all files with remote server (excluding GÇIT, datasets, flycheck, Python
# venv and other caches and datasets).

rsync -e "ssh -p 6969" \
      -avzhP \
      --delete \
      --exclude checkpoints/ \
      --exclude .git \
      --exclude __pycache__ \
      --exclude '.#*' \
      --exclude 'flycheck_*' \
      --exclude .gitignore \
      --exclude .venv \
      --exclude .cache \
      --exclude results \
      --exclude audio \
      --exclude images \
      /home/david/Documents/UPC/Cuatrimestre\ 9/Bachelor\'s\ Thesis/ \
      root@recomprehension.com:/var/www/html/thesis/
