#!/bin/bash


# Update to vector

rsync -avzhP \
      --exclude checkpoints/ \
      --exclude .git \
      --exclude __pycache__ \
      --exclude '.#*' \
      --exclude 'flycheck_*' \
      --exclude .gitignore \
      --exclude .venv \
      /home/david/Documents/UPC/Cuatrimestre\ 9/Bachelor\'s\ Thesis/Code/ \
      dalvarez@q.vectorinstitute.ai:~/"Bachelor\'s\ Thesis/"
